---
- name: Install Docker Engine
  hosts: all
  tasks:

    - name: Upgrade apt packages
      become: true
      ansible.builtin.apt:
        upgrade: true
        update_cache: true

    - name: Install prerequisites for Docker repository
      become: true
      ansible.builtin.apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg2
          - lsb-release

    - name: Add docker apt key
      become: true
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add docker apt repo
      become: true
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        update_cache: true

    - name: Install docker and its dependencies
      become: true
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          # - docker-buildx-plugin
          # - docker-compose-plugin
        state: present

    - name: Ensure group "docker" exists
      ansible.builtin.group:
        name: docker
        state: present

    - name: Adding  to docker group {{ ansible_user }}
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Start and enable docker daemon
      become: true
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Start and enable containerd daemon
      become: true
      ansible.builtin.service:
        name: containerd
        state: started
        enabled: true
