version: '3.3'
project_name: ${PROJECTNAME}
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - "post_db"
          - "comment_db"
  ui:
    build:
      context: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${REDDIT_PORT}:${REDDIT_PORT}/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      back_net:
        aliases:
          - "post"
      front_net:
        aliases:
          - "post"
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      back_net:
        aliases:
          - "comment"
      front_net:
        aliases:
          - "comment"

volumes:
  post_db:

networks:
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
